blastn -db BG-SNP-Denovo/BG.SNP.denovo.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 4 -query ch-xshang24du-1.fa -out ch-xshang24du-1.Y1.m8 &
blastn -db BG-SNP-Denovo/BG.SNP.denovo.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 4 -query ch-xshang24du-2.fa -out ch-xshang24du-2.Y1.m8 &
blastn -db BG-SNP-Denovo/BG.SNP.denovo.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 4 -query ch-xshang24du-3.fa -out ch-xshang24du-3.Y1.m8 &
blastn -db BG-SNP-Denovo/BG.SNP.denovo.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 4 -query ch-xshang6du-1.fa -out ch-xshang6du-1.Y1.m8 &
blastn -db BG-SNP-Denovo/BG.SNP.denovo.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 4 -query ch-xshang6du-2.fa -out ch-xshang6du-2.Y1.m8 &
blastn -db BG-SNP-Denovo/BG.SNP.denovo.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 4 -query ch-xshang6du-3.fa -out ch-xshang6du-3.Y1.m8 &
blastn -db WG-SNP-Denovo/WG.SNP.denovo.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 4 -query ch-xxia24du-1.fa -out ch-xxia24du-1.8424.m8 &
blastn -db WG-SNP-Denovo/WG.SNP.denovo.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 4 -query ch-xxia24du-2.fa -out ch-xxia24du-2.8424.m8 &
blastn -db WG-SNP-Denovo/WG.SNP.denovo.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 4 -query ch-xxia24du-3.fa -out ch-xxia24du-3.8424.m8 &
blastn -db WG-SNP-Denovo/WG.SNP.denovo.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 4 -query ch-xxia6du-1.fa -out ch-xxia6du-1.8424.m8 &
blastn -db WG-SNP-Denovo/WG.SNP.denovo.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 4 -query ch-xxia6du-2.fa -out ch-xxia6du-2.8424.m8 &
blastn -db WG-SNP-Denovo/WG.SNP.denovo.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 4 -query ch-xxia6du-3.fa -out ch-xxia6du-3.8424.m8 &
blastn -db BG-SNP-Denovo-ALL/BG-SNP-Denovo-ALL.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 4 -query ch-xxia24du-1.fa -out ch-xxia24du-1.Y1.m8 &
blastn -db BG-SNP-Denovo-ALL/BG-SNP-Denovo-ALL.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 4 -query ch-xxia24du-2.fa -out ch-xxia24du-2.Y1.m8 &
blastn -db BG-SNP-Denovo-ALL/BG-SNP-Denovo-ALL.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 4 -query ch-xxia24du-3.fa -out ch-xxia24du-3.Y1.m8 &
blastn -db BG-SNP-Denovo-ALL/BG-SNP-Denovo-ALL.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 4 -query ch-xxia6du-1.fa -out ch-xxia6du-1.Y1.m8 &
blastn -db BG-SNP-Denovo-ALL/BG-SNP-Denovo-ALL.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 4 -query ch-xxia6du-2.fa -out ch-xxia6du-2.Y1.m8 &
blastn -db BG-SNP-Denovo-ALL/BG-SNP-Denovo-ALL.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 4 -query ch-xxia6du-3.fa -out ch-xxia6du-3.Y1.m8 &
blastn -db WG-SNP-Denovo-ALL/WG-SNP-Denovo-ALL.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 4 -query ch-xshang24du-1.fa -out ch-xshang24du-1.8424.m8 &
blastn -db WG-SNP-Denovo-ALL/WG-SNP-Denovo-ALL.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 4 -query ch-xshang24du-2.fa -out ch-xshang24du-2.8424.m8 &
blastn -db WG-SNP-Denovo-ALL/WG-SNP-Denovo-ALL.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 4 -query ch-xshang24du-3.fa -out ch-xshang24du-3.8424.m8 &
blastn -db WG-SNP-Denovo-ALL/WG-SNP-Denovo-ALL.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 4 -query ch-xshang6du-1.fa -out ch-xshang6du-1.8424.m8 &
blastn -db WG-SNP-Denovo-ALL/WG-SNP-Denovo-ALL.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 4 -query ch-xshang6du-2.fa -out ch-xshang6du-2.8424.m8 &
blastn -db WG-SNP-Denovo-ALL/WG-SNP-Denovo-ALL.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 4 -query ch-xshang6du-3.fa -out ch-xshang6du-3.8424.m8 &