blastn -db BG-SNP-Denovo-ALL/BG-SNP-Denovo-ALL.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 2 -query chang-24du-1.fa -out chang-24du-1.Y1.m8 &
blastn -db BG-SNP-Denovo-ALL/BG-SNP-Denovo-ALL.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 2 -query chang-24du-2.fa -out chang-24du-2.Y1.m8 &
blastn -db BG-SNP-Denovo-ALL/BG-SNP-Denovo-ALL.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 2 -query chang-24du-3.fa -out chang-24du-3.Y1.m8 &
blastn -db BG-SNP-Denovo-ALL/BG-SNP-Denovo-ALL.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 2 -query chang-6du-1.fa -out chang-6du-1.Y1.m8 &
blastn -db BG-SNP-Denovo-ALL/BG-SNP-Denovo-ALL.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 2 -query chang-6du-2.fa -out chang-6du-2.Y1.m8 &
blastn -db BG-SNP-Denovo-ALL/BG-SNP-Denovo-ALL.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 2 -query chang-6du-3.fa -out chang-6du-3.Y1.m8 &
blastn -db BG-SNP-Denovo/BG.SNP.denovo.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 2 -query xigua-24du-1.fa -out xigua-24du-1.Y1.m8 &
blastn -db BG-SNP-Denovo/BG.SNP.denovo.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 2 -query xigua-24du-2.fa -out xigua-24du-2.Y1.m8 &
blastn -db BG-SNP-Denovo/BG.SNP.denovo.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 2 -query xigua-24du-3.fa -out xigua-24du-3.Y1.m8 &
blastn -db BG-SNP-Denovo/BG.SNP.denovo.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 2 -query xigua-6du-1.fa -out xigua-6du-1.Y1.m8 &
blastn -db BG-SNP-Denovo/BG.SNP.denovo.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 2 -query xigua-6du-2.fa -out xigua-6du-2.Y1.m8 &
blastn -db BG-SNP-Denovo/BG.SNP.denovo.fa -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 2 -query xigua-6du-3.fa -out xigua-6du-3.Y1.m8 &
blastn -db WG-SNP-Denovo/WG.SNP.denovo.fa  -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 2 -query chang-24du-1.fa -out chang-24du-1.8424.m8 &
blastn -db WG-SNP-Denovo/WG.SNP.denovo.fa  -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 2 -query chang-24du-2.fa -out chang-24du-2.8424.m8 &
blastn -db WG-SNP-Denovo/WG.SNP.denovo.fa  -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 2 -query chang-24du-3.fa -out chang-24du-3.8424.m8 &
blastn -db WG-SNP-Denovo/WG.SNP.denovo.fa  -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 2 -query chang-6du-1.fa -out chang-6du-1.8424.m8 &
blastn -db WG-SNP-Denovo/WG.SNP.denovo.fa  -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 2 -query chang-6du-2.fa -out chang-6du-2.8424.m8 &
blastn -db WG-SNP-Denovo/WG.SNP.denovo.fa  -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 2 -query chang-6du-3.fa -out chang-6du-3.8424.m8 &
blastn -db WG-SNP-Denovo-ALL/WG-SNP-Denovo-ALL.fa  -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 2 -query xigua-24du-1.fa -out xigua-24du-1.8424.m8 &
blastn -db WG-SNP-Denovo-ALL/WG-SNP-Denovo-ALL.fa  -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 2 -query xigua-24du-2.fa -out xigua-24du-2.8424.m8 &
blastn -db WG-SNP-Denovo-ALL/WG-SNP-Denovo-ALL.fa  -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 2 -query xigua-24du-3.fa -out xigua-24du-3.8424.m8 &
blastn -db WG-SNP-Denovo-ALL/WG-SNP-Denovo-ALL.fa  -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 2 -query xigua-6du-1.fa -out xigua-6du-1.8424.m8 &
blastn -db WG-SNP-Denovo-ALL/WG-SNP-Denovo-ALL.fa  -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 2 -query xigua-6du-2.fa -out xigua-6du-2.8424.m8 &
blastn -db WG-SNP-Denovo-ALL/WG-SNP-Denovo-ALL.fa  -max_target_seqs 3 -evalue 1e-5 -outfmt 6 -num_threads 2 -query xigua-6du-3.fa -out xigua-6du-3.8424.m8 &